import { type NextPage } from "next";
import Head from "next/head";
import { VideoCard } from "@/components/client/card";
import { NavBar } from "@/components/client/navbar";
import { api } from "@/server/utils/api";
import { Pagination } from "@/components/client/pagination";
import { cardPerPage } from "@/config";
import { Montserrat } from "@next/font/google";
import { Footer } from "@/components/client/footer";
import { Banner } from "@/components/client/banner";

const montserrat = Montserrat({
  subsets: ["latin", "cyrillic"],
  weight: "900",
});

const Home: NextPage = () => {
  const cards = api.client.getCards.useQuery({ skip: 0, take: cardPerPage });
  const cardCount = api.client.getCardCount.useQuery();

  return (
    <>
      <Head>
        <title>Media app</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/hjbjh.png" />
      </Head>

      <main className={`bg-black`}>
        <NavBar />

        <Banner image={"/banner-test.jpeg"} />

        {!cards.data ? (
          ""
        ) : (
          <div className="parent-div mx-auto grid grid-cols-1 gap-4 p-4 2xl:container lg:grid-cols-3">
            {cards.data.map((data) => (
              <VideoCard
                key={data?.thumbnailSprite?.sprite as string}
                id={data?.id}
                image={data?.thumbnailSprite?.sprite as string}
                slug={data.videoUuidSlug}
                likes={data?.likes?.likesCount as string}
                views={data.views?.viewsCount as string}
                title={data.title}
                time={data.durationTime}
              />
            ))}
          </div>
        )}
      </main>

      <div
        className={`${montserrat.className} row mt-[30px] flex w-full justify-center gap-4`}
      >
        <Pagination
          firstPage=""
          link="page/"
          currentPage={1}
          totalItems={cardCount.data ? cardCount.data : 0}
        />
      </div>
      <Banner image={"/banner-test.jpeg"} />

      <Footer />
    </>
  );
};

export default Home;
